package projinit

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/polyapi/polyglot/src/config"
	"github.com/polyapi/polyglot/src/exitcode"
)

const gitHook = `#!/bin/sh
# Installed by polyapi init. Runs deploy prepare so generated comments stay in review.
if command -v polyapi >/dev/null 2>&1; then
  polyapi deploy prepare
fi
`

const githubWorkflow = `name: Poly deploy
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install polyapi
        run: curl -fsSL https://raw.githubusercontent.com/polyapi/polyglot/main/scripts/install.sh | sh
      - name: Deploy
        env:
          POLY_API_KEY: ${{ secrets.POLY_API_KEY_PROD }}
          POLY_API_BASE_URL: ${{ secrets.POLY_API_BASE_URL_PROD }}
        run: |
          export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"
          polyapi deploy push --non-interactive --yes
`

const gitlabCI = `# Generated by polyapi init. Add POLY_API_KEY_PROD and POLY_API_BASE_URL_PROD as CI/CD variables.
# Grant the job permission to push if your deploy step commits receipts.
stages: [deploy]
deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - curl -fsSL https://raw.githubusercontent.com/polyapi/polyglot/main/scripts/install.sh | sh
    - export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"
    - polyapi deploy push --non-interactive --yes
`

// GitInit runs `git init` when dest is not already a repository and git is on PATH.
func GitInit(root string, stdout io.Writer) (bool, error) {
	if isGitRepo(root) {
		return false, nil
	}
	git := findBinary("git")
	if git == "" {
		return false, nil
	}
	if stdout != nil {
		fmt.Fprintln(stdout, "Initializing git repository…")
	}
	cmd := exec.Command(git, "init")
	cmd.Dir = root
	cmd.Stdout = stdout
	cmd.Stderr = stdout
	if err := RunCmd(cmd); err != nil {
		return false, wrap(exitcode.Failure, "git init", err)
	}
	return true, nil
}

func isGitRepo(root string) bool {
	st, err := os.Stat(filepath.Join(root, ".git"))
	return err == nil && (st.IsDir() || st.Mode().IsRegular())
}

// EnsureIgnore lists .poly/ (and language junk) in .gitignore when dest is a git repo.
func EnsureIgnore(root, lang string) (config.GitignoreAction, error) {
	act, err := config.EnsurePolyGitignored(root)
	if err != nil {
		return 0, err
	}
	if act == config.GitignoreSkippedNotGit {
		return act, nil
	}
	extras := []string{".DS_Store"}
	if strings.EqualFold(lang, "python") {
		extras = append(extras, ".venv/", "venv/", "__pycache__/", "*.pyc")
	} else {
		extras = append(extras, "node_modules/", "dist/")
	}
	gitignore := filepath.Join(root, ".gitignore")
	raw, err := os.ReadFile(gitignore)
	if err != nil {
		return act, wrap(exitcode.Failure, "read .gitignore", err)
	}
	text := string(raw)
	changed := false
	for _, line := range extras {
		if ignoreHasLine(text, line) {
			continue
		}
		if text != "" && !strings.HasSuffix(text, "\n") {
			text += "\n"
		}
		text += line + "\n"
		changed = true
	}
	if changed {
		if err := os.WriteFile(gitignore, []byte(text), 0o644); err != nil {
			return act, wrap(exitcode.Failure, "write .gitignore", err)
		}
		if act == config.GitignoreAlreadyPresent {
			act = config.GitignoreAppended
		}
	}
	return act, nil
}

func ignoreHasLine(contents, want string) bool {
	for _, line := range strings.Split(contents, "\n") {
		if strings.TrimSpace(line) == want {
			return true
		}
	}
	return false
}

// EnsureHook writes .git/hooks/pre-commit when the project has no husky/pre-commit yet.
func EnsureHook(root string, stdout io.Writer) (bool, error) {
	if !isGitRepo(root) {
		return false, nil
	}
	if hasManagedHooks(root) {
		return false, nil
	}
	hookDir := filepath.Join(root, ".git", "hooks")
	// Worktrees store .git as a file; skip rather than invent a hook path.
	if st, err := os.Stat(filepath.Join(root, ".git")); err == nil && !st.IsDir() {
		return false, nil
	}
	if err := os.MkdirAll(hookDir, 0o755); err != nil {
		return false, wrap(exitcode.Failure, "create git hooks directory", err)
	}
	path := filepath.Join(hookDir, "pre-commit")
	if fileExists(path) {
		return false, nil
	}
	if err := os.WriteFile(path, []byte(gitHook), 0o755); err != nil {
		return false, wrap(exitcode.Failure, "write git pre-commit hook", err)
	}
	if runtime.GOOS != "windows" {
		_ = os.Chmod(path, 0o755)
	}
	if stdout != nil {
		fmt.Fprintln(stdout, "Installed git pre-commit hook (polyapi deploy prepare)")
	}
	return true, nil
}

func hasManagedHooks(root string) bool {
	if st, err := os.Stat(filepath.Join(root, ".husky")); err == nil && st.IsDir() {
		return true
	}
	if fileExists(filepath.Join(root, ".pre-commit-config.yaml")) || fileExists(filepath.Join(root, ".pre-commit-config.yml")) {
		return true
	}
	return false
}

// EnsureCI writes a GitHub Actions or GitLab CI workflow when none exists.
func EnsureCI(root, provider string, stdout io.Writer) (string, error) {
	p := strings.ToLower(strings.TrimSpace(provider))
	if p == "" {
		p = "github"
	}
	switch p {
	case "github":
		if hasGitHubWorkflow(root) {
			return "", nil
		}
		path := filepath.Join(root, ".github", "workflows", "poly-deploy.yml")
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return "", wrap(exitcode.Failure, "create .github/workflows", err)
		}
		if err := os.WriteFile(path, []byte(githubWorkflow), 0o644); err != nil {
			return "", wrap(exitcode.Failure, "write GitHub workflow", err)
		}
		if stdout != nil {
			fmt.Fprintln(stdout, "Wrote .github/workflows/poly-deploy.yml")
		}
		return path, nil
	case "gitlab":
		path := filepath.Join(root, ".gitlab-ci.yml")
		if fileExists(path) {
			return "", nil
		}
		if err := os.WriteFile(path, []byte(gitlabCI), 0o644); err != nil {
			return "", wrap(exitcode.Failure, "write .gitlab-ci.yml", err)
		}
		if stdout != nil {
			fmt.Fprintln(stdout, "Wrote .gitlab-ci.yml")
		}
		return path, nil
	default:
		return "", nil
	}
}

func hasGitHubWorkflow(root string) bool {
	dir := filepath.Join(root, ".github", "workflows")
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		n := strings.ToLower(e.Name())
		if strings.HasSuffix(n, ".yml") || strings.HasSuffix(n, ".yaml") {
			return true
		}
	}
	return false
}

// NextSteps is the post-init checklist printed to the user.
func NextSteps(root, lang, provider, venvName string, loggedIn bool) string {
	var b strings.Builder
	b.WriteString("Next steps:\n")
	if !loggedIn {
		b.WriteString("  1. polyapi auth login\n")
		b.WriteString("  2. polyapi generate\n")
	} else {
		b.WriteString("  1. polyapi generate\n")
	}
	if strings.EqualFold(lang, "python") {
		b.WriteString("  Activate the virtualenv: " + ActivateHint(root, venvName) + "\n")
	}
	p := strings.ToLower(strings.TrimSpace(provider))
	if p == "" {
		p = "github"
	}
	switch p {
	case "github":
		b.WriteString("  Create a GitHub repository, add a remote, and push main.\n")
		b.WriteString("  Add repository secrets POLY_API_KEY_PROD and POLY_API_BASE_URL_PROD.\n")
		b.WriteString("  Set Actions workflow permissions to Read and write:\n")
		b.WriteString("    https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions\n")
		b.WriteString("    https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository\n")
	case "gitlab":
		b.WriteString("  Create a GitLab project, add a remote, and push main.\n")
		b.WriteString("  Add CI/CD variables POLY_API_KEY_PROD and POLY_API_BASE_URL_PROD.\n")
	}
	b.WriteString("  Scaffold a function with `polyapi function init --name helloWorld --type server`.\n")
	return b.String()
}
