#!/usr/bin/env python3
"""Fixture PolyAPI language adapter (protocol 1). Stdin JSON → stdout JSON."""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

OPS = [
    "capabilities",
    "generate",
    "discover",
    "inspect",
    "extract",
    "prepare",
    "write_receipt",
    "parse_function",
    "clear",
]


def main() -> int:
    argv = [a for a in sys.argv[1:] if a != "adapter"]
    raw = sys.stdin.read()
    if not raw.strip():
        sys.stderr.write("fixture adapter: empty stdin\n")
        return 2
    req = json.loads(raw)
    op = req.get("op")
    req_id = req.get("id")
    lang = req.get("lang") or "python"
    root = Path(req.get("project_root") or ".")
    protocol = int(os.environ.get("POLY_FIXTURE_PROTOCOL", "1"))
    min_protocol = int(os.environ.get("POLY_FIXTURE_MIN_PROTOCOL", str(protocol)))

    def reply(ok: bool, result=None, error=None, warnings=None, exit_code: int = 0) -> int:
        json.dump(
            {
                "protocol": protocol,
                "id": req_id,
                "ok": ok,
                "op": op,
                "result": result,
                "warnings": warnings or [],
                "error": error,
            },
            sys.stdout,
        )
        sys.stdout.write("\n")
        return exit_code

    if op == "capabilities":
        return reply(
            True,
            {
                "protocol": protocol,
                "min_protocol": min_protocol,
                "ops": OPS,
                "lang": lang,
                "sdk_version": "fixture-1",
            },
        )

    if protocol != 1:
        return reply(
            False,
            None,
            {"code": "protocol", "message": f"fixture protocol {protocol}"},
            exit_code=11,
        )

    if op == "generate":
        out = root / "generated" / "sdk.txt"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("generated by fixture adapter\n", encoding="utf-8")
        rel = str(out.relative_to(root)).replace("\\", "/")
        return reply(True, {"files_written": [rel], "stats": {"files": 1}})

    if op == "discover":
        ext = "py" if lang == "python" else "ts"
        return reply(
            True,
            {
                "deployables": [
                    {
                        "type": "variable",
                        "name": "apiKey",
                        "context": "billing",
                        "file": f"src/billing/vari/apiKey.{ext}",
                        "export": "polyConfig",
                        "content_hash": None,
                        "receipt": None,
                    }
                ]
            },
        )

    if op == "extract":
        payload = {
            "type": "variable",
            "name": "apiKey",
            "context": "billing",
            "description": "fixture variable",
            "secret": False,
            "value": "from-source",
        }
        params = req.get("params") or {}
        file = params.get("file") or ""
        if file:
            abs_path = root / file
            if abs_path.exists():
                text = abs_path.read_text(encoding="utf-8")
                m = re.search(r"['\"]name['\"]\s*[:=]\s*['\"]([^'\"]+)", text)
                if m:
                    payload["name"] = m.group(1)
                m = re.search(r"['\"]context['\"]\s*[:=]\s*['\"]([^'\"]+)", text)
                if m:
                    payload["context"] = m.group(1)
        return reply(
            True,
            {
                "payload": payload,
                "content_hash": "fixture-hash",
                "meta": {"lang": lang, "file": file},
            },
        )

    if op == "inspect":
        files = (req.get("params") or {}).get("files") or []
        return reply(
            True,
            {
                "items": [
                    {
                        "file": f,
                        "type": "server-function",
                        "code": "",
                        "description": "",
                        "arguments": [],
                        "returns": {"type": "string", "description": ""},
                        "disable_ai": False,
                    }
                    for f in files
                ]
            },
        )

    if op == "prepare":
        files = (req.get("params") or {}).get("files") or []
        names = [f if isinstance(f, str) else f.get("file") for f in files]
        return reply(True, {"changed_files": [], "skipped": names})

    if op == "write_receipt":
        return reply(True, {"ok": True})

    if op == "parse_function":
        params = req.get("params") or {}
        code = ""
        file = params.get("file") or ""
        if file:
            path = Path(file)
            if not path.is_absolute():
                path = root / file
            if path.exists():
                code = path.read_text(encoding="utf-8")
        return reply(
            True,
            {
                "name": params.get("name"),
                "language": lang,
                "code": code,
                "kind": params.get("kind"),
                "arguments": [{"key": "text", "name": "text", "type": {"type": "string"}}],
                "returnType": {"type": "string"},
            },
        )

    if op == "clear":
        target = root / "generated"
        if target.is_dir():
            for child in target.iterdir():
                child.unlink()
            target.rmdir()
        return reply(True, {"ok": True})

    _ = argv
    return reply(
        False,
        None,
        {"code": "unknown_op", "message": f"unknown op {op}"},
        exit_code=2,
    )


if __name__ == "__main__":
    sys.exit(main())
