#!/usr/bin/env node
"use strict";
/**
 * Fixture PolyAPI language adapter (protocol 1). Stdin JSON → stdout JSON.
 */
const fs = require("fs");
const path = require("path");

const OPS = [
  "capabilities",
  "generate",
  "discover",
  "inspect",
  "extract",
  "prepare",
  "write_receipt",
  "parse_function",
  "clear",
];

const raw = fs.readFileSync(0, "utf8");
if (!raw.trim()) {
  process.stderr.write("fixture adapter: empty stdin\n");
  process.exit(2);
}
const req = JSON.parse(raw);
const op = req.op;
const reqId = req.id;
const lang = req.lang || "typescript";
const root = req.project_root || ".";
const protocol = Number(process.env.POLY_FIXTURE_PROTOCOL || "1");
const minProtocol = Number(process.env.POLY_FIXTURE_MIN_PROTOCOL || String(protocol));

function reply(ok, result, error, warnings, exitCode) {
  process.stdout.write(
    JSON.stringify({
      protocol,
      id: reqId,
      ok,
      op,
      result: result ?? null,
      warnings: warnings || [],
      error: error ?? null,
    }) + "\n",
  );
  process.exit(exitCode ?? 0);
}

if (op === "capabilities") {
  reply(true, {
    protocol,
    min_protocol: minProtocol,
    ops: OPS,
    lang,
    sdk_version: "fixture-1",
  });
}

if (protocol !== 1) {
  reply(false, null, { code: "protocol", message: `fixture protocol ${protocol}` }, [], 11);
}

if (op === "generate") {
  const outDir = path.join(root, "generated");
  fs.mkdirSync(outDir, { recursive: true });
  const out = path.join(outDir, "sdk.txt");
  fs.writeFileSync(out, "generated by fixture adapter\n");
  const rel = path.relative(root, out).split(path.sep).join("/");
  reply(true, { files_written: [rel], stats: { files: 1 } });
}

if (op === "discover") {
  const ext = lang === "python" ? "py" : "ts";
  reply(true, {
    deployables: [
      {
        type: "variable",
        name: "apiKey",
        context: "billing",
        file: `src/billing/vari/apiKey.${ext}`,
        export: "polyConfig",
        content_hash: null,
        receipt: null,
      },
    ],
  });
}

if (op === "extract") {
  const file = (req.params && req.params.file) || "";
  const payload = {
    type: "variable",
    name: "apiKey",
    context: "billing",
    description: "fixture variable",
    secret: false,
    value: "from-source",
  };
  const abs = path.join(root, file);
  if (file && fs.existsSync(abs)) {
    const text = fs.readFileSync(abs, "utf8");
    const name = text.match(/name:\s*['"]([^'"]+)/);
    if (name) payload.name = name[1];
    const ctx = text.match(/context:\s*['"]([^'"]+)/);
    if (ctx) payload.context = ctx[1];
  }
  reply(true, {
    payload,
    content_hash: "fixture-hash",
    meta: { lang, file },
  });
}

if (op === "inspect") {
  const files = (req.params && req.params.files) || [];
  reply(true, {
    items: files.map((file) => ({
      file,
      type: "server-function",
      code: "",
      description: "",
      arguments: [],
      returns: { type: "string", description: "" },
      disable_ai: false,
    })),
  });
}

if (op === "prepare") {
  const files = (req.params && req.params.files) || [];
  const names = files.map((f) => (typeof f === "string" ? f : f.file));
  reply(true, { changed_files: [], skipped: names });
}

if (op === "write_receipt") {
  reply(true, { ok: true });
}

if (op === "parse_function") {
  const params = req.params || {};
  let code = "";
  const file = params.file || "";
  if (file) {
    const abs = path.isAbsolute(file) ? file : path.join(root, file);
    if (fs.existsSync(abs)) {
      code = fs.readFileSync(abs, "utf8");
    }
  }
  reply(true, {
    name: params.name,
    language: lang,
    code,
    kind: params.kind,
    arguments: [{ key: "text", name: "text", type: { type: "string" } }],
    returnType: { type: "string" },
  });
}

if (op === "clear") {
  const target = path.join(root, "generated");
  if (fs.existsSync(target)) {
    for (const name of fs.readdirSync(target)) {
      fs.unlinkSync(path.join(target, name));
    }
    fs.rmdirSync(target);
  }
  reply(true, { ok: true });
}

reply(false, null, { code: "unknown_op", message: `unknown op ${op}` }, [], 2);
